version: '2'
services:
  testproject-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/testProject/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=testProject
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
